# Generated by Django 5.2 on 2025-05-10 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_teachersubject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersubject',
            name='subject',
            field=models.CharField(choices=[('math', 'Matematica'), ('physics', 'Fisica'), ('latin', 'Latino'), ('history', 'Storia'), ('science', 'Scienze'), ('english', 'Inglese'), ('french', 'Francese')], max_length=50),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('math', 'Matematica'), ('physics', 'Fisica'), ('latin', 'Latino'), ('history', 'Storia'), ('science', 'Scienze'), ('english', 'Inglese'), ('french', 'Francese')], max_length=50)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_lessons', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_lessons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
