# Generated by Django 5.2 on 2025-06-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_availability_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
