# Generated by Django 5.2 on 2025-06-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_lesson_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='Cognome',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='Nome',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
